# Car Price Prediction using Dummy variables using ONE HOT ENCODING

In [51]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
import numpy as np

In [52]:
df = pd.read_csv("carprices.csv")
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [53]:
dfle = df
dfle['Car Model'] = le.fit_transform(dfle['Car Model']) #Assigning values for car models
dfle['Car Model']

0     1
1     1
2     1
3     1
4     1
5     0
6     0
7     0
8     0
9     2
10    2
11    2
12    2
Name: Car Model, dtype: int32

In [54]:
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [55]:
X = dfle[['Car Model','Mileage','Age(yrs)']].values

In [56]:
X

array([[    1, 69000,     6],
       [    1, 35000,     3],
       [    1, 57000,     5],
       [    1, 22500,     2],
       [    1, 46000,     4],
       [    0, 59000,     5],
       [    0, 52000,     5],
       [    0, 72000,     6],
       [    0, 91000,     8],
       [    2, 67000,     6],
       [    2, 83000,     7],
       [    2, 79000,     7],
       [    2, 59000,     5]], dtype=int64)

In [57]:
y = dfle['Sell Price($)'].values
y

array([18000, 34000, 26100, 40000, 31500, 29400, 32000, 19300, 12000,
       22000, 20000, 21000, 33000], dtype=int64)

In [58]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer  # this will split the column in same no. as there are text variables in column.
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])],remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)

C:\Users\Harshendra singh bha\AppData\Local\Temp\ipykernel_15612\2353794963.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X=np.array(columnTransformer.fit_transform(X),dtype=np.str)


In [59]:
X

array([['0.0', '1.0', '0.0', '69000.0', '6.0'],
       ['0.0', '1.0', '0.0', '35000.0', '3.0'],
       ['0.0', '1.0', '0.0', '57000.0', '5.0'],
       ['0.0', '1.0', '0.0', '22500.0', '2.0'],
       ['0.0', '1.0', '0.0', '46000.0', '4.0'],
       ['1.0', '0.0', '0.0', '59000.0', '5.0'],
       ['1.0', '0.0', '0.0', '52000.0', '5.0'],
       ['1.0', '0.0', '0.0', '72000.0', '6.0'],
       ['1.0', '0.0', '0.0', '91000.0', '8.0'],
       ['0.0', '0.0', '1.0', '67000.0', '6.0'],
       ['0.0', '0.0', '1.0', '83000.0', '7.0'],
       ['0.0', '0.0', '1.0', '79000.0', '7.0'],
       ['0.0', '0.0', '1.0', '59000.0', '5.0']], dtype='<U32')

In [60]:
X = X[:,1:]# it says give all rows leaving the column index 1

In [62]:
X

array([['1.0', '0.0', '69000.0', '6.0'],
       ['1.0', '0.0', '35000.0', '3.0'],
       ['1.0', '0.0', '57000.0', '5.0'],
       ['1.0', '0.0', '22500.0', '2.0'],
       ['1.0', '0.0', '46000.0', '4.0'],
       ['0.0', '0.0', '59000.0', '5.0'],
       ['0.0', '0.0', '52000.0', '5.0'],
       ['0.0', '0.0', '72000.0', '6.0'],
       ['0.0', '0.0', '91000.0', '8.0'],
       ['0.0', '1.0', '67000.0', '6.0'],
       ['0.0', '1.0', '83000.0', '7.0'],
       ['0.0', '1.0', '79000.0', '7.0'],
       ['0.0', '1.0', '59000.0', '5.0']], dtype='<U32')

## Training the model using Linear Regression

In [66]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [72]:
model.fit(X,y)

C:\Users\Harshendra singh bha\anaconda3\lib\site-packages\sklearn\utils\validation.py:964: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(


LinearRegression()

In [69]:
model.predict([[0,1,45000,4]])

array([36991.31721063])

In [73]:
model.predict([[1,0,86000,7]])

array([11080.74313217])

In [74]:
model.score(X,y)

C:\Users\Harshendra singh bha\anaconda3\lib\site-packages\sklearn\base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


0.9417050937281083